### ISSUE TITLE
Can't resolve './dev'

### ISSUE THREAD

**Issue by ChiaraSammarco** [codewithbernard/react-redux-firebase#2]
Hi, 
I've downloaded your repo for testing, but I've got the following error: 

`Failed to compile.
./src/config/keys.js
Module not found: Can't resolve './dev' in 'XXXXX\src\config'`

Thanks for your help.

**Comment by davidcosama** [comment]
You have to create a file named dev.js with the following content

export const FirebaseConfig = {
  apiKey: "<Web API Key>",
  authDomain: "<Project ID>.firebaseapp.com",
  databaseURL: "<Database url>"
};

It's possible to have to create the "prod.js" as well. For testing, you can use the same data.

For more information you can follow the article of a more basic version here https://medium.com/quick-code/how-to-integrate-react-redux-and-firebase-in-3-simple-steps-c44804a6af38
